" pathogen
"  plugins: 
"   sensible
"   Vim Tmux Navigator
"   nerdtree
"
"   ctrlp
"   vim-surround
"   DidYouMean
"   nerd Commenter

"runtime bundle/vim-pathogen/autoload/pathogen.vim
"execute pathogen#infect()
syntax on
filetype plugin indent on

" find current buffer in tree
nnoremap <leader>r :NERDTreeFind<cr>
nnoremap <leader>d :NERDTreeToggle<CR>

" ctrlp settings
let g:ctrlp_map = '<c-p>'
let g:ctrlp_cmd = 'CtrlP'
" ignore files
set wildignore+=*/tmp/*,*.so,*.swp,*.zip,*/node_modules/* 

set smarttab
set shiftwidth=2
set tabstop=2

" view open buffers
nnoremap <leader>b :ls<cr>:b<space>

" Grep fix
set grepprg=grep\ -n\ $*

set number
set cursorline
set noswapfile
set mouse=a

" function toggles
" toggle highlighting on/off
nnoremap <F4> :set hlsearch! hlsearch?<CR>
" toggle word wrap
nnoremap <F5> :set nowrap! nowrap?<CR>

" jj exits insert mode
inoremap jj <esc>
" makes vim move down a 'cursor' line for when line is word wrapped
nnoremap j gj
nnoremap k gk
" default open tabs to right and down
set splitright
set splitbelow

cabbrev ww :w
nnoremap ; :
nnoremap : ;
" Auto-save a file when you leave insert mode
autocmd InsertLeave * if expand('%') != '' | update | endif
